default_stages: [push]
repos:
- repo: local
  hooks:

    - id: isort
      name: imports
      types: [python]
      language: system
      entry: isort

    - id: format
      name: code-format
      types: [python]
      language: system
      entry: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: ^test/integration
